server:
  port:8080

spring:
  # Redis配置 用于随机串防重放缓存
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
         max-active:8
         max-idle:8
         min-idle:2

# 接口签名全局配置
api:
  # 请求有效时间 单位秒 超过则请求过期拦截
  sign-expire: 300
  # 预设单客户端密钥信息 生产环境全部存入数据库多客户端管理
  app:
     key: test_app_key_123456
     secret: test_app_secret_654321_abcdef123456