spring:
  application:
    name: security-client
  boot:
    admin:
      client:
        url: 'http://127.0.0.1:8080'
        instance:
          name: security-client
        username: admin
        password: 123456
  security:
    user:
      name: admin
      password: 123456

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
#      base-path: /actuator 去掉访问前缀，防止访问404
      exposure:
        include: '*'

server:
  port: 8081

logging:
  file:
    name: 'logic-client.log'
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
