server:
  port: 8080

spring:
  application:
    name: admin-security-server
  security:
    user:
      name: "admin"
      password: "123456"



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"