server:
  tomcat:
    max-swallow-size: 10MB
  port: 8081

minio:
  endpoint: http://192.168.3.71:9000
  access-key: minioadmin
  secret-key: NJben@1234
  bucket-name: image
  secure: false
  region: us-east-1

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB